### ISSUE TITLE
Rename all budgie-remix references to Ubuntu Budgie

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/plymouth-theme#1]
All references of budgie-remix needs to be changed to "budgie" - this is to allow upload for 16.10

**Comment by RohanVilloth** [comment]
Umm.. Isn't it supposed to be renamed as **Ubuntu Budgie**? :confused:

**Comment by fossfreedom** [comment]
Does it matter?.  What is the naming convention for the other Plymouth flavours?

**Comment by RohanVilloth** [comment]
Other flavor's Plymouth theme package and source package names:
- [plymouth-theme-ubuntu-gnome-logo](http://packages.ubuntu.com/xenial/plymouth-theme-ubuntu-gnome-logo) from [ubuntu-gnome-default-settings](http://packages.ubuntu.com/source/xenial/ubuntu-gnome-default-settings)
- [plymouth-theme-ubuntu-mate-logo](http://packages.ubuntu.com/xenial/plymouth-theme-ubuntu-mate-logo) from [ubuntu-mate-artwork](http://packages.ubuntu.com/source/xenial/ubuntu-mate-artwork)
- [plymouth-theme-kubuntu-logo](http://packages.ubuntu.com/xenial/plymouth-theme-kubuntu-logo) from [kubuntu-settings](http://packages.ubuntu.com/source/xenial/kubuntu-settings)
- [plymouth-theme-xubuntu-logo](http://packages.ubuntu.com/xenial/plymouth-theme-xubuntu-logo) from [xubuntu-artwork](http://packages.ubuntu.com/source/xenial/xubuntu-artwork)
- [plymouth-theme-ubuntustudio](http://packages.ubuntu.com/xenial/plymouth-theme-ubuntustudio) from [ubuntustudio-look](http://packages.ubuntu.com/source/xenial/ubuntustudio-look)

See, they all name their plymouth theme packages after their flavor name, not the desktop name. :grin: So, our's should be **plymouth-theme-ubuntu-budgie-logo** and  **plymouth-theme-ubuntu-budgie-text**  for the binary packages.

**Comment by fossfreedom** [comment]
k - makes sense. ok the control file needs to change to plymouth-theme-ubuntubudgie (no hyphen like ubuntustudio)

**Comment by RohanVilloth** [comment]
I think it's better to have it like **plymouth-theme-ubuntu-budgie** and follow the convention set by Ubuntu GNOME and Ubuntu MATE.

On second thought, I think it's better if we merge this plymouth-theme source too to the main artwork source. Coz none of the other flavors have it separately. But I've to have a look at the way they handle all the licensing and attribution information. :confused:
